apiVersion: v1
kind: ImageStream
metadata:
  labels:
    role: jenkins-slave
  name: nodejs-6-chrome
spec:
  tags:
  - from:
      kind: DockerImage
      name: docker.io/outtherelabs/nodejs-6-centos7-chrome:latest
    name: latest

